### ISSUE TITLE
Windscibe

### ISSUE THREAD

**Issue by samkonix** [retenet/rete#7]
Hi,

I try rete with generic vpn support for windscribe vpn

This is my config :
```
browser:
  name: brave

profile:
  default: personal
  list: [htb, lan, media, personal, shopping, work]

vpn:
  provider: generic
  user: ******
  pass: ******
  config: /home/sam/bicycle.ovpn
```

The container creation fail

```
[i] Downloading Latest brave Image...
[i] Downloading Latest tunle Image...
[i] Retreiving Running Containers...
[i] Starting tunle_generic...
[i] Starting brave...
[-] Failed to Start Container.
[-] 404 Client Error: Not Found ("No such container: tunle_generic")
```

How can activate more debug trace to see what append ?

Regards.
